# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Event Schemas for use by the Properties Service'

#### PARAMETERS
Parameters:
  Stage:
    Type: String
    Default: Local
    AllowedValues:
      - Local
      - Dev
      - Prod

#### RESOURCES
Resources:
  EventRegistry:
    Type: AWS::EventSchemas::Registry
    Properties: 
      Description: 'Event schemas for Unicorn Properties'
      RegistryName: !Sub "{{resolve:ssm:/UniProp/${Stage}/UnicornPropertiesNamespace}}"

  EventRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties: 
      RegistryName: !GetAtt EventRegistry.RegistryName
      Policy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowExternalServices
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - schemas:DescribeCodeBinding
              - schemas:DescribeRegistry
              - schemas:DescribeSchema
              - schemas:GetCodeBindingSource
              - schemas:ListSchemas
              - schemas:ListSchemaVersions
              - schemas:SearchSchemas
            Resource:
              - !GetAtt EventRegistry.RegistryArn
              - !Sub "arn:${AWS::Partition}:schemas:${AWS::Region}:${AWS::AccountId}:schema/${EventRegistry.RegistryName}*"
